### ISSUE TITLE
Foto2vam.py missing flipFirst argument to CreateTrainingEncodings Tool

### ISSUE THREAD

**Issue by Trichinosis** [ChrisTopherTa54321/foto2vam#2]
Foto2vam.py line 28, change
`params = argparse.Namespace(inputPath=inputPath, filter="*.png,*.jpg", normalizeSize=150, normalize=True, numJitters=10, numThreads=4, pydev=False, recursive=True, debugPose = False)`
to:
`params = argparse.Namespace(inputPath=inputPath, filter="*.png,*.jpg", normalizeSize=150, normalize=True, numJitters=10, numThreads=4, pydev=False, recursive=True, debugPose = False, flipFirst=False)
`
in order for foto2vam to run successfully w/ all latest commits.

[ancillary issue deleted, was using wrong base.json from v4]

**Comment by ChrisTopherTa54321** [comment]
Thanks!
